- assets/ajaxify.js.liquid
- locales/de.json
- locales/en.default.json
- locales/es.json
- locales/fr.json
- locales/pt-BR.json
- locales/pt-PT.json
Fixes #234 
cc/ @afshing @stevebosworth
> i18n ajaxify cart strings

- assets/ajaxify.js.liquid
Adding in those missing semicolons you mentioned.
cc/ @stevebosworth
> Added missing semi-colons

- assets/timber.scss.liquid
> Centering the search bar vertically within the nav

- locales/de.json
- locales/en.default.json
- locales/es.json
- locales/fr.json
- locales/pt-BR.json
- locales/pt-PT.json
- templates/cart.liquid
Pretty unhelpful label, so removed it here.
> Removed 'product' label from cart page

- assets/timber.scss.liquid
Making at-query more intuitive
> make at-query smarter and not require null values for min-max

- assets/timber.scss.liquid
> Revert "make at-query smarter and not require null values for min-max"

- config/settings.html
- locales/de.json
- locales/en.default.json
- locales/es.json
- locales/fr.json
- locales/pt-BR.json
- locales/pt-PT.json
- snippets/onboarding-empty-collection.liquid
- snippets/onboarding-featured-collections.liquid
- snippets/onboarding-featured-products.liquid
- templates/index.liquid
Fixes #363 
cc @carolineschnapp
> Home page to homepage

- assets/timber.scss.liquid
Minor syntax update of #359 and link to docs.
cc/ @jtgrenz
> Make the at-query more intuitive for min-max calls

- assets/timber.scss.liquid
> Prevent cart button from being full width

- config/settings_data.json
- templates/customers/account.liquid
- templates/customers/activate_account.liquid
- templates/customers/addresses.liquid
- templates/customers/login.liquid
- templates/customers/order.liquid
- templates/customers/register.liquid
- templates/customers/reset_password.liquid
Fixes #382.
Anything else related to this that needs to be removed, @carolineschnapp @fredryk?
> Remove customer layout setting

- snippets/oldIE-js.liquid
Moving away from Google's SVN in favour of CDNJS.
@stevebosworth
> New link to HTML5 shiv

- templates/collection.liquid
> switched grid-item class to BEM

- templates/product.liquid
Fixes #406  
@suture @stevebosworth
> Remove anchor from next/prev product links

- spec/helpers/i18n_helper.rb
That test should not work with multiple keywords. This should fix it.
ping @cshold 
/cc @haani
> [Fix] Excluded keyword in i18n tests

- assets/timber.scss.liquid
Fix mixin defaults and a typo in `backface`
> Mixin fixes (typo, defaults)

- templates/blog.liquid
Update to #483 - change anchor link for comment URL.
cc/ @suture @carolineschnapp
> Update comment link anchor

- assets/timber.scss.liquid
Corrected "Henseforth" to "Henceforth"
> Spelling correction

- templates/list-collections.liquid
> use grid-uniform class

- layout/theme.liquid
> Fix mobile account link style

- assets/ajax-cart.js.liquid
> literal error

- assets/timber.scss.liquid
- bower.json
> Update bower version

- assets/ajax-cart.js.liquid
- snippets/ajax-cart-template.liquid
Fix for https://github.com/Shopify/shopify-themes/issues/3471 and to address https://github.com/Shopify/Timber/pull/522/files/15fdc677beeafa15f47ce50aefdf2b10bffdf864#r66314153
@NathanPJF :eyes: when you can! Thx :}
cc @cshold
> [Timber] update Shopify Scripts ajax prices

- assets/ajax-cart.js.liquid
Fixes issue mentioned here https://github.com/Shopify/Timber/pull/563#issuecomment-242297641
> Fix JS syntax on StorefrontExpressButtons

- index.html
Fixes https://github.com/Shopify/Timber/issues/590
@tanema 
cc @stevebosworth
> [Docs] Update theme syncing to link to theme kit
