assets/ajaxify.js.liquid
Strings were being brought in with double quotes, breaking the `title` attribute and including double quotes around the string. This fixes it.
cc/ @stevebosworth
=> Fixed how strings are appended in ajax cart

assets/timber.js.liquid
Fixes #312 to make sure duplicate parameters don't get added to the URL.
Via second answer [here](http://stackoverflow.com/questions/7171099/how-to-replace-url-parameter-with-javascript-jquery).
[Demo here](https://carson-dev-shop.myshopify.com/collections/all?view=grid)
cc/ @stevebosworth @Woland2k
=> Fixed broken replaceUrlParam function

assets/timber.scss.liquid
Fixes #314
As shown in [this example](http://timber-test-3.myshopify.com/products/die-cast-cars-with-case-8985?variant=1098771568), the "Sold Out" looks to be floated beside the price. Turns out that all instances of elements that extend our headers by using a class (in this case `<span class="h2">`) don't get set as block, but inherit their element's layout.
The issues only occurs when the CTA on the product page immediately follows the price. The quantity selector between them hides the problem.
This forces all extended headers to be blocks. Can test at https://carson-dev-shop.myshopify.com/
cc/ @spuddick @stevebosworth @mpiotrowicz
=> Make all headers blocks

assets/timber.scss.liquid, config/settings.html
Had a 5 digit hex color and a missing hyphen in a class name.
@stevebosworth Using `rte--header` as it is a variation of `.rte`, not a child.
cc/ @mpiotrowicz
=> Minor rte and default setting update

assets/timber.scss.liquid, templates/cart.liquid
As per [this Shopify forum post](https://ecommerce.shopify.com/c/partners-technical/t/timber-theme-bug-227059), `{% if item.properties.size > 0 %}` will never run so here it is removed. The `for` loop is more than capable of handling this on its own.
Fixes #317
cc @stevebosworth
=> Update cart properties size check

locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, snippets/onboarding-empty-collection.liquid, snippets/onboarding-featured-collections.liquid, snippets/onboarding-featured-products.liquid, templates/collection.liquid, templates/index.liquid
@cshold @mpiotrowicz 
Adds some default blank state products and collections to help with onboarding when the theme is first installed in a blank shop.
=> Default blankstates

assets/ajaxify.js.liquid, snippets/onboarding-empty-collection.liquid, snippets/onboarding-featured-collections.liquid, snippets/onboarding-featured-products.liquid
Global onboarding images have `http:` hardcoded in there. This PR removes that to make them relative. I'll update our public themes too if this gets the green light.
=> Protocol-relative image URLS

snippets/product-grid-item.liquid, snippets/product-list-item.liquid
Removing unnecessary `current_collection` variable for handling collection-relative product URLs.
=> Collection relative links

assets/ajaxify.js.liquid, snippets/ajax-cart-template.liquid
Replace buggy regex (invalid if product name contains a “-“) with data directly from the API response
=> remove Ajaxify regex

layout/theme.liquid
The customer templates have some inline JS that is dependant on `shopify_common.js`, so for the time being I suggest moving it back to the top of the page.
A better solution will be added to the wishlist that can hopefully remove the inline JS from the customer templates all together.
=> Move customer js back to top of file

templates/cart.liquid
Using underscores rather than camelcase for liquid variables
=> Underscores for liquid variables

assets/timber.js.liquid, layout/theme.liquid
The library was there, but never initialized. Faster tapping for all!
cc @stevebosworth @mpiotrowicz
=> Init fastclick

assets/gift-card.scss.liquid, templates/gift_card.liquid
Added QR code to printed gift cards. A few other very minor style updates.
- Center text/logo on print version
- Reduce header padding so printed version fits on one page
Demo - https://checkout.shopify.com/gift_cards/4790585/preview#
@stevebosworth @carolineschnapp
=> QR code on printed gift card template

assets/timber.scss.liquid
Adds a URL input type to the reset - especially needed when embedding MailChimp forms to get a uniformed look.
=> Add the URL input type

locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, snippets/product-grid-item.liquid, snippets/product-list-item.liquid, snippets/search-result-grid.liquid, snippets/search-result.liquid, templates/search.liquid
Updated the product grid/list item snippets and search results to use a more readable sale prices.
Now there are three ways to show the price:
1. On sale price, with regular price crossed out
2. On sale *from* price (if variants have other prices), with regular price crossed out
3. Regular price
Fixes #209 
I've also slightly updated the list item layout so that the price never breaks below the product image.
Thoughts, @stevebosworth @jholl @tranhelen @graygilmore?
=> Updated product sale presentation in grid/list

templates/customers/account.liquid
In the rare case there are more than 20 orders for a user, add pagination so they're always available.
cc/ @fredryk @stevebosworth
=> Paginate orders if more than 20

assets/timber.scss.liquid, snippets/blog-sidebar.liquid, snippets/footer.liquid, templates/article.liquid, templates/blog.liquid, templates/customers/activate_account.liquid, templates/customers/addresses.liquid, templates/customers/login.liquid, templates/customers/register.liquid, templates/customers/reset_password.liquid, templates/page.contact.liquid, templates/product.liquid
Form selectors:
- The form selectors are too specific right now. Using `input[type="XXXX"]` means a single class won't override it.
- By moving to simply `input`, we can style all inputs the same and override them with classes whe needed.
- `radio` and `checkbox` styles are overwritten on the element level
- `input[type="image"]` is overwritten on the element-level.
- This comes up with `additional_checkout_buttons` (PayPal especially_
Lists
- Allow list styles to be applied in RTE too
Updated templates:
- Updated various `ul` elements to include `no-bullets` class
- Updated customer templates to make forms vertical, rather than default horizontal
=> Reudced selector specificity. New form and list defaults.

assets/timber.scss.liquid, templates/article.liquid, templates/customers/activate_account.liquid, templates/customers/login.liquid, templates/customers/register.liquid, templates/customers/reset_password.liquid, templates/page.contact.liquid
Class was changed at some point to `hidden--label`. This reverts it back to `label-hidden`, which is what our docs show.
=> Revert to original hidden class name. Add better clipping

assets/timber.scss.liquid
@cshold 
Fixes syntax for clip rule to properly support IE8+
https://msdn.microsoft.com/en-us/library/ie/ms530748%28v=vs.85%29.aspx
=> fixed sytax of clip in fallback text

locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, snippets/collection-sidebar.liquid
@pauldpritchard brought up a good point, listing out `type` and `vendor` in the collection sidebar makes it seem Shopify has the native ability to sort the current content by them. In reality, the links pull you out of the current collection/tag to the top-level type or vendor.
Thoughts? @mpiotrowicz @carolineschnapp @fredryk
=> Remove type and vendor links in collection sidebar

circle.yml
@cshold This should remove `gh-pages` from ever running in CircleCI
=> Remove gh-pages from CircleCI

index.html
Updated `at-query` mixin docs to go with #367
=> v2.1.1 Doc updates

assets/timber.scss.liquid
Old IE can't use placeholder, so make the invisible labels visible. The absolute positioning was never removed, and the clip is reset.
=> Hidden label fix for old ie

templates/search.liquid
There was a decent chunk of duplicate code on the search template. This reduces that by moving the `if search performed` and `if no results` conditionals only affect the title of the page.
cc/ @mpiotrowicz @stevebosworth @carolineschnapp
=> Removed duplicate search layout code

locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, snippets/collection-sidebar.liquid
Catch-all links to create *All **collection*** links were not i18n friendly. This fixes that.
cc @carolineschnapp
=> Add i18n for catch-all collection tags

assets/timber.scss.liquid
Since `.is-transitioning` is added/removed to `.is-moved-by-drawer`, the transition sometimes is removed from the element at the wrong time. This adds the transition to the root element, making sure the animation never gets choppy.
cc @stevebosworth
=> Safer drawer transition implementation

templates/customers/addresses.liquid
Fixes #385
Instead of using multiple `paginate` tags as the issue suggests (which also works), this wraps the entire template in the paginate tags to solve the same issue.
cc @stevebosworth @schaeken
=> Fix broken edit/delete buttons on address template with pagination

templates/customers/activate_account.liquid, templates/customers/login.liquid, templates/customers/reset_password.liquid
Minor style updates for customer area forms to ensure they're more unified in design.
cc/ @mpiotrowicz @stevebosworth
=> Customer form style updates

locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, snippets/product-grid-item.liquid, snippets/social-meta-tags.liquid, templates/collection.list.liquid, templates/search.liquid
Following on the work by @schaeken in https://github.com/Shopify/shopify-themes/pull/1259, using i18n-friendly translations for **From $xx.xx**.
This covers the Twitter card meta data, product grid items, and search results (grid and list views).
=> i18n for varying price label

assets/timber.scss.liquid
`rect` wasn't there, so `clip` didn't work at all.
=> Fixed broken clip property

assets/ico-select.svg.liquid
Use the text rather than border color for the custom select arrow.
cc/ @carolineschnapp @stevebosworth
=> Use text color rather than border for select element

layout/theme.liquid
Fixes #392 by wrapping the cart link in a div. We want it to be display block, but don't want the actual anchor reaching invisibly across the page.
=> Fix layout issue in header

snippets/oldIE-js.liquid
Linking against Google Code is problematic because
- The version is not pinned
- Google Code is being shut down
- The `/svn` endpoint was probably not intended to be a CDN
=> Link against cdnjs instead of googlecode for html5shiv

snippets/ajax-cart-template.liquid
Allow the ajax cart to submit as a normal form even if the ajax is unable to update the cart fast enough. This happens if you change the product quantity in the cart and press enter to submit the form.
=> Let ajax cart submit as normal form with proper quantity

assets/timber.js.liquid
Fix for #413 - remove hard coded colon. If desired, add it to the string file itself.
=> Remove compare price colon - hardcoded in JS

assets/ajax-cart.js.liquid, snippets/ajax-cart-template.liquid
When products have custom properties they weren't differentiated in the ajax cart because the variant ID was used, rather than the 'line' of the cart it was one. This PR:
- Uses the 'line' of the cart item to adjust quantity
- Removes use of variant ID in JS
- Updates jQuery selector variables to be prefaced with `$`
- Adds line item properties to the ajax cart template
- Uses the plus/minus icons in the quantity selectors
@carolineschnapp @stevebosworth (same update as Brooklyn theme)
=> Add line item properties to ajax cart. Cleaned up ajax cart JS.

assets/timber.scss.liquid, locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, snippets/product-grid-item.liquid, templates/cart.liquid, templates/collection.list.liquid, templates/product.liquid, templates/search.liquid
@cshold @mpiotrowicz 
Switched the cart over to a table layout for improved a11y
=> switch cart over to table layout

assets/timber.scss.liquid
* Removes unnecessary prefixing for `transition`, `linear-gradient`, `transform`, and `box-sizing`
* Replaces `prefix` mixin with `prefixer` inspired by [Bourbon's prefixer](https://github.com/thoughtbot/bourbon/blob/master/app/assets/stylesheets/addons/_prefixer.scss).  Encourages only using necessary prefixes.
* Docs will have to be updated.
Test store: http://timber-dev.myshopify.com/
=> Prefix mixins cleanup

assets/timber.js.liquid
Fixes #421 
Use liquid conditional to set `ajaxCart.load` function after drawer opens
@stevebosworth
=> Fix JS error when ajax cart disabled

layout/theme.liquid, templates/gift_card.liquid
Since Shopify only supports IE8+ these aren't (and shouldn't) being
used.
=> Remove unused IE conditionals

snippets/social-meta-tags.liquid
Fixes #435 for deprecated `product` Twitter cards.
cc @stevebosworth @fredryk
=> Update twitter card meta tags

assets/ajax-cart.js.liquid, snippets/ajax-cart-template.liquid
**Issue:** With a single product in the cart, changing the quantity to 0 and then hitting enter tries to submit the form (not ajax), while the blur event on the quantity input removes the product from the cart. It's a race to see which happens first, but most of the time the form gives an ugly JS alert saying it can't submit an empty cart.
**Fix:** This PR stops the cart submission if the ajax quantity is currently running.
cc/ @stevebosworth (same update as Brooklyn)
=> Prevent cart form submission while ajax running

_includes/footer.html
Remove timber@ email to curb non-framework requests.
cc @mpiotrowicz @stevebosworth
=> Remove timber support email

snippets/social-meta-tags.liquid
Follow up to https://github.com/Shopify/Timber/pull/436, label and data meta tags will be ignored when Twitter product cards are deprecated on July 3rd.
cc @carolineschnapp
=> Remove data/label meta fields from twitter cards

templates/collection.list.liquid
During a theme review with the Shopify team having different paginate by counts for the collection and collection list views came up as an issue.  Here are the steps to recreate the potential bug with mismatched pagination counts:
- Create a collection with 25 or more products
- The collection template will paginate over 3 pages
- Go to the last page
- Switch from collection to collection.list view
- Now you will see "Sorry, there are no products in this collection" since the page does not exist with the higher list pagination count.
It was incredibly helpful having Timber as a guideline to work from for our first theme.  Hopefully this small change will help someone else.
=> Change collection list paginate by count to match collection

assets/timber.js.liquid
When opening/closing drawers, proper focus wasn't set. This fixes that.
Pulled from [Brooklyn theme](https://themes.shopify.com/themes/brooklyn/styles/brooklyn).
cc/ @mpiotrowicz
=> Add focus to drawer when opened

assets/timber.js.liquid
Simplifying the call to `trapFocus` and `removeTrapFocus`
=> No need to call drawer prototype for focus trap

templates/collection.liquid
Currently Timber displays the onboarding message when `collection.handle == 'all'` returns no products.  There is one case where `/collection/all` does contain products, but if you use non-existent tags on `/collection/all` it shows onboarding rather than a "no products found" message.
I know it is a pretty rare edge case, but it came up during a Shopify theme review for submission.
=> Better handling for onboarding in collections

_includes/footer.html, _includes/head.html, index.html
@cshold I was taking a look at Timber today and noticed a few little nitpicky things on the website.
* Changed one link from shopify.ca to shopify.com.
* Changed a bunch of Brochure/docs links to HTTPS because why not (users get redirected to HTTPS anyway).
* Fixed capitalization/spacing: Github => GitHub, Master Card => MasterCard, Mailchimp => MailChimp.
* `Who Is This For` heading changed to `Who This Is For`
* Changed wording for browser support - it sounded a bit awkward given that the stock Android browser is named Browser.
=> Timber website nitpicks: capitalization, minor wording tweaks, etc

Gemfile.lock, assets/timber.scss.liquid
Addresses #454 
Decided to make sure `max-width: 100%` is applied to all iframes as well.
=> max-width to contain all images by default

layout/theme.liquid
=> Remove fallback icon wrapper when no fallback text is needed

templates/product.liquid
Lets Google Analytics use a product's sku rather than variant ID.
@fredryk
=> Add data-sku to option on product page

assets/timber.js.liquid
This is a fix to address a small bug in our last fix for the chrome iframe bug. Shopify Themes issue originally logged and updated here https://github.com/Shopify/shopify-themes/issues/1326#issuecomment-138707078 (private repo)
To summarize, when multiple videos are displayed on a page, things work fine initially. When moving to another page and then using the browsers back button, the previous videos will all be the same source. 
Chromium issue logged here https://code.google.com/p/chromium/issues/detail?id=395791
@cshold this should be good to go as its the same code we have already merges on all our internal timber themes. Just wanna double check before merging
=> [Timber] fix responsive video bug

assets/timber.scss.liquid, config/settings_schema.json
I added that value in the stylesheet in order to get this setting working.
Address #460
=> Using the settings.logo_max_width value in styles

assets/timber.js.liquid, layout/theme.liquid, templates/article.liquid
A pending PR in Shopify (https://github.com/Shopify/shopify/pull/57450) will reload the page after a comment form submission with either `#comments` or `#comment-form` as a hash in the URL.
- `#comments` already works as expected on a successful post
- `#comment-form` will be added when the form has errors, jumping the page down to the anchor on the form so the user can fix the mistakes
This PR removes the hacky JS that got around having accurate URL hashes and updates the IDs.
cc @Shopify/themes-team @mac-adam-chaieb 
FYI @Shopify/theme-support, this can be a reference for updating other themes. Ping me with any questions.
=> Update article comment form ids

assets/timber.js.liquid, assets/timber.scss.liquid, config/settings_data.json, config/settings_schema.json, layout/theme.liquid
Updates for https://github.com/Shopify/Timber/issues/486
We In addition to going through content checklist here https://docs.shopify.com/themes/theme-development/theme-store-requirements/content-style-guide
The Shopify themes team also decided to try and steer away from using the word Ajax in the theme settings as it's not meaningful to most merchants. The new option is a dropdown for cart type 
[![alt](https://screenshot.click/19-40-gqlvn-4mf8f.jpg)](https://screenshot.click/19-40-gqlvn-4mf8f.jpg)
Drawer will trigger the ajax drawer, Page will disable ajax and redirect to /cart on form submission. Additionally, developers and designers are also encouraged to use Modal, Flipdown, or other design types in the dropdown as wish. 
@virginiastart @cshold I don't think I missed anything, but a …
=> Content style update

layout/theme.liquid, locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json
Adding Shopify newsletter form as default for the newsletter form. Once the merchant adds their MailChimp URL then we can switch the form over to use MailChimp. This way merchants will be collecting customers info in the early stages when they haven't set up their MailChimp account or even 5 years later when they finally discover MailChimp!
Review @karocena @cshold  :eyes:
=> Add Shopify newsletter fallback

locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, templates/article.liquid, templates/blog.liquid, templates/index.liquid
Having `comments_with_count` causes the i18n page to display "Comments comments with count". This changes it to just "Comments with count".
review: @matcaissy 
cc @cshold
=> Update blog comments json

layout/theme.liquid, templates/customers/login.liquid
Since `/account/register` is available, and since one can create a account from any page using a `POST` request, let's show the account creation link when accounts are required — same as when accounts are optional.
=> Show account creation link when accounts are required

config/settings_schema.json
There are some leftover text in the theme settings from the days of `settings.html`. This only confuses people since theme settings are coded differently now. 
@cshold
=> Remove color setting help text

templates/customers/addresses.liquid
Issue raised here: https://github.com/Shopify/Timber/issues/489
=> Paginated addresses js bug

layout/theme.liquid
This fixes the changes in the way Safari interprets zooming and overflow on objects. As Apple consider their changes to be the right way to do things, they probably aren’t going to be changing the behaviour any time soon.
=> Fix iOS Safari off canvas scaling issues

assets/timber.js.liquid, layout/theme.liquid
Fixes #516 and fixes #507
The original purpose of the cart/drawer setting was for what happens after you add a product to the cart. It's confusing the way it's worded in settings as you'd think the drawer would be completely disabled when selecting 'Page'.
This PR completely removes the cart drawer when 'Page' is selected.
@stevebosworth @carolineschnapp @t-kelly @m-ux
=> Disable cart drawer when setting is page

assets/ajax-cart.js.liquid, assets/timber.scss.liquid, locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, snippets/ajax-cart-template.liquid, templates/cart.liquid
Fix for https://github.com/Shopify/shopify-themes/issues/2953
@NathanPJF :eyes: when you can, thanks :)
CC @carolineschnapp @cshold
=> [Timber] add cart discounts

assets/ajax-cart.js.liquid
Addresses https://github.com/Shopify/Timber/issues/529
Use the preexisting `isUpdating` bool to prevent additional ajax requests from firing until the cart has finished updating.
@cshold Can I get your 👀 on this as well?
=> Fix ajax cart request

assets/ajax-cart.js.liquid, assets/timber.js.liquid, layout/theme.liquid
Hey :)
I think it's a good idea to start using events in Timber instead of callbacks to make it easy to tap into interface changes. I also want to add events to the ajax_cart.js file, what you think?
=> Add events to notify of drawer opening / closing

layout/theme.liquid, snippets/blog-sidebar.liquid, snippets/collection-sidebar.liquid, templates/article.liquid, templates/blog.liquid, templates/customers/account.liquid, templates/customers/order.liquid, templates/search.liquid
Fix for https://github.com/Shopify/shopify-themes/issues/3527 (improving theme accessibility) and removed Stripe in credit cart payment whitelist.
**Demo: [link](http://timber-a11y.myshopify.com/?key=a0335d17c5dc8dbd88dc16199fc42229156bf8b8ba253d9d26aceb39170de2a4&preview_theme_id=110651457)**
cc @cshold @schaeken 👀
=> [Timber] update a11y headings and remove stripe icon whitelist

locales/en.default.json, locales/fr.json, locales/pt-PT.json
Fixes to name convention "home page" from previous versions of "frontpage" or "homepage" or similar conventions within content.
=> [Timber]home page text change

locales/de.json, locales/en.default.json, locales/es.json, locales/fr.json, locales/pt-BR.json, locales/pt-PT.json, snippets/ajax-cart-template.liquid, templates/cart.liquid
Fix for https://github.com/Shopify/shopify-themes/issues/3524, which updates better a11y quantity input screenreader text. Also updated cart submit inputs to buttons.
cc @ruairiphackett @cshold mind taking a look? 👀
=> [Timber] update cart a11y qty input and button

assets/ajax-cart.js.liquid, snippets/ajax-cart-template.liquid, templates/cart.liquid, templates/customers/order.liquid
Changing ajax cart, customer order and cart templates to use key for line items instead of ids. 
cc/ @NathanPJF
=> changing line item ids to use keys

assets/ajax-cart.js.liquid
Themes using `ajax-cart` with Amazon Payments button are currently broken because of the script tag inserted along with the button.
Handlebars + script tag in template = 💥 
Let's add a callback after the cart has been updated where we can initialize every button needed on storefront.
@Krystosterone @cshold please review 👯 
Next step is modifying `shopify-themes` with these changes too. @cshold can you shed some light on the difference between `ajax-cart.js` and `ajaxify.js` in `shopify-themes` ?
*dont merge until https://github.com/Shopify/shopify/pull/80604*
=> Add StorefrontExpressButtons.initialize in cartCallback

templates/product.liquid
~~Fix rounding issue caused by using `divided_by` Math filter.~~
~~> Divides an output by a number. The output is rounded down to the nearest integer.~~
~~i.e. 3499.95 was being rounded down to 3499~~
~~See: https://help.shopify.com/themes/liquid/filters/math-filters#divided_by~~
~~Bring `price` implementation inline with usage guidelines. No longer produces warning in Google's Structured Data Testing Tool for values greater than 999.99 that use comma separator for readability.~~
~~> Use '.' (Unicode 'FULL STOP' (U+002E)) rather than ',' to indicate a decimal point. Avoid using these symbols as a readability separator.~~
~~See: http://schema.org/price~~
Updated pull request based on solution in comments provided by @cshold
=> Fix structured data price rounding issue and usage warning

templates/customers/addresses.liquid
[Shopify's liquid checklist](https://help.shopify.com/themes/development/theme-store-requirements/theme-file-requirements#customers-addresses-liquid) requires that errors are outputted properly on the `customer/addresses.liquid` file. This PR makes Timber comply with Shopify's theme requirements. 
@cshold for review
=> Show errors in customer address forms

layout/theme.liquid
See http://blog.jquery.com/2016/01/08/jquery-2-2-and-1-12-released/.
Should be backwards compatible.
Fixes a lot of bugs and improves performance.
=> Update jQuery to latest 1.x stable version

snippets/ajax-cart-template.liquid
Removed two stray </div> tags which were causing improper rendering of DOM on AjaxCart update. Previously, any additional products placed in the cart after the first product would be rendered outside their intended parent `.ajaxcart__inner`. products are now rendered correctly within `.ajaxcart__inner`.
Refer to Issue #593 for more information.
=> Fix for Issue #593 (Bug in AjaxCart template)

snippets/social-meta-tags.liquid
As stated in the docs, named image sizes are deprecated.
See: https://help.shopify.com/themes/liquid/filters/url-filters#named-size-parameters
=> Remove deprecated named size parameters from social-meta-tags.liquid

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md
* Deprecation warning that Timber is no longer supported.  
* Messaging for developers to use [Slate](https://github.com/Shopify/slate) to follow Shopify theme development.
* Updated info in README about getting support and links to additional resources.
@Shopify/themes-team 
/cc @cshold
=> Deprecation warning
